# Generated by Django 5.1.4 on 2026-05-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('editor', 'Redator'), ('user', 'Leitor')], db_index=True, default='user', max_length=10),
        ),
    ]
