import type { User, BannedUser } from '../types';

export const MOCK_USERS: User[] = [
  {
    id: 1,
    name: 'Maria Silva',
    email: 'maria@interpop.com',
    role: 'admin',
    avatarInitial: 'M',
    joinedAt: '10 jan 2025',
    postsCount: 34,
  },
  {
    id: 2,
    name: 'Carlos Mendes',
    email: 'carlos@interpop.com',
    role: 'admin',
    avatarInitial: 'C',
    joinedAt: '15 jan 2025',
    postsCount: 21,
  },
  {
    id: 3,
    name: 'Ana Costa',
    email: 'ana@email.com',
    role: 'user',
    avatarInitial: 'A',
    joinedAt: '03 fev 2025',
    postsCount: 0,
  },
  {
    id: 4,
    name: 'Pedro Rocha',
    email: 'pedro@email.com',
    role: 'user',
    avatarInitial: 'P',
    joinedAt: '18 fev 2025',
    postsCount: 0,
  },
  {
    id: 5,
    name: 'Julia Farias',
    email: 'julia@interpop.com',
    role: 'admin',
    avatarInitial: 'J',
    joinedAt: '22 fev 2025',
    postsCount: 15,
  },
  {
    id: 6,
    name: 'Ricardo Lima',
    email: 'ricardo@email.com',
    role: 'user',
    avatarInitial: 'R',
    joinedAt: '01 mar 2025',
    postsCount: 0,
  },
  {
    id: 7,
    name: 'Fernanda Melo',
    email: 'fernanda@email.com',
    role: 'user',
    avatarInitial: 'F',
    joinedAt: '12 mar 2025',
    postsCount: 0,
  },
  {
    id: 8,
    name: 'Lucas Barros',
    email: 'lucas@email.com',
    role: 'user',
    avatarInitial: 'L',
    joinedAt: '05 abr 2025',
    postsCount: 0,
  },
  {
    id: 9,
    name: 'Tatiane Souza',
    email: 'tatiane@email.com',
    role: 'user',
    avatarInitial: 'T',
    joinedAt: '19 abr 2025',
    postsCount: 0,
  },
  {
    id: 10,
    name: 'Bruno Carvalho',
    email: 'bruno@email.com',
    role: 'user',
    avatarInitial: 'B',
    joinedAt: '27 abr 2025',
    postsCount: 0,
  },
];

export const MOCK_BANNED: BannedUser[] = [
  {
    id: 1,
    userId: 11,
    userName: 'Marcos Spammer',
    userEmail: 'marcos_spam@email.com',
    avatarInitial: 'M',
    reason:
      'Envio massivo de mensagens promocionais não solicitadas nos comentários.',
    bannedAt: '14 mar 2025 — 09:42',
    bannedBy: 'Maria Silva',
  },
  {
    id: 2,
    userId: 12,
    userName: 'Rodrigo Fake',
    userEmail: 'rodrigo_fake@email.com',
    avatarInitial: 'R',
    reason:
      'Criação de conta com informações falsas e uso de identidade de terceiros.',
    bannedAt: '02 abr 2025 — 14:17',
    bannedBy: 'Julia Farias',
  },
  {
    id: 3,
    userId: 13,
    userName: 'Aline Ofensiva',
    userEmail: 'aline_off@email.com',
    avatarInitial: 'A',
    reason:
      'Comentários com linguagem ofensiva e assédio a outros usuários após aviso prévio.',
    bannedAt: '21 abr 2025 — 11:05',
    bannedBy: 'Carlos Mendes',
  },
];
