# Generated by Django 5.1.4 on 2026-05-19 03:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BanRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(help_text='Motivação da solicitação.')),
                ('trigger_message', models.TextField(blank=True, help_text='Mensagem/conteúdo específico que originou a solicitação.')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada')], db_index=True, default='pending', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, help_text='Justificativa do admin ao decidir.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ban_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(help_text='Redator que solicitou (null se conta excluída).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ban_requests_made', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(help_text='Usuário-alvo da solicitação.', on_delete=django.db.models.deletion.CASCADE, related_name='ban_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ban_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='ban_request_status_9b1d94_idx')],
            },
        ),
    ]
